services:
  - type: web
    name: anso-msf-validator
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: voila --port=$PORT --no-browser --enable_nbextensions=True anso_msf_validator.ipynb
    autoDeploy: false