services:
  - type: web
    name: anso-msf-validator
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    preInstallCommand: playwright install
    startCommand: voila --port=$PORT --no-browser --Voila.ip=0.0.0.0 --Voila.base_url=/ anso_msf_validator.ipynb
    autoDeploy: false
    healthCheckPath: /voila